### PR TITLE
 files with corrected pre

### PR DESCRIPTION
**Pull request by SokolovskyVadim**
But apparently in some new files, I did not save an empty line after HTML = (

### CODE REVIEW

**Review by pluhin — CHANGES_REQUESTED** [review]
You have conflicts, could you please resolve them

**Comment by SokolovskyVadim** [comment]
I have conflicts in 1 file or all of them? And how i can find the conflicts?

**Comment by SokolovskyVadim** [comment]
In a fact, i just delete all empty "pre", in all files....

**Comment by SokolovskyVadim** [comment]
Did I fix the conflicts?

**Review by pluhin — APPROVED** [review]
All good, approved

**Pull request merged**
