### PR TITLE
Site.by

### PR DESCRIPTION
**Pull request by vladshavel**
can you check additional part

### CODE REVIEW

**Review by pluhin — CHANGES_REQUESTED** [review]
Why did you delete not your files? You do need to to that, could you please put them back

**Comment by vladshavel** [comment]
Which files I deleted?

**Comment by vladshavel** [comment]
And how I can put them back?
Can I use git on another PC?

**Comment by pluhin** [comment]
> Which files I deleted?

In your  pull request a lot of deleted files
https://github.com/pluhin/sc.it-academy.by/pull/187/files

**Comment by vladshavel** [comment]
Ok,
I just should put this files back?
I think I copy them on my pc in my work

**Comment by pluhin** [comment]
> And how I can put them back?

Clone my repo in some temp folder, but not into your project, checkout to our branch and copy missing in your project


> Can I use git on another PC?

Yes, you can

**Comment by vladshavel** [comment]
How can I do this?
Git clone your repository?
Then copy files in my folder?

**Comment by pluhin** [comment]
> How can I do this?
> Git clone your repository?
> Then copy files in my folder?

Yes, if we are talking about put back removed files

**Comment by vladshavel** [comment]
Ok
I will try to do this

**Comment by vladshavel** [comment]
i think i did it

**Comment by pluhin** [comment]
I think it was bad idea, I try to solve problem

**Comment by pluhin** [comment]
I resolve issue with deleted files, 
Your files, in the attachment, need to add just changed files (folder site.by and files part1.html and part2.html) then commit  them. 
You need to recreate PR then,  
[vshavel.zip](https://github.com/pluhin/sc.it-academy.by/files/2774370/vshavel.zip)

**Comment by vladshavel** [comment]
i changed these files
but nothing changed in my folder and there is nothing to commit
i will try to commit everything with forms

**Pull request closed without merging**
