### PR TITLE
Home task 07

### PR DESCRIPTION
**Pull request by viktarradzin**

### CODE REVIEW

**Comment by viktarradzin** [comment]
found repository conflicts, will do synchronization before our lesson today

**Comment by viktarradzin** [comment]
Failed to implement hidden string recovery

**Review by pluhin — APPROVED** [review]
Good, approved

**Comment by pluhin** [comment]
> Failed to implement hidden string recovery

What do you mean "hidden"?

**Comment by viktarradzin** [comment]
> > Failed to implement hidden string recovery
> 
> What do you mean "hidden"?

I managed to hide the lines when clicking on tr, but failed to open them back, in the last additional task on jQuery, need to learn jQuery, all is fine thank you

**Review by pluhin — APPROVED** [review]
Good, approved

**Pull request merged**
